export const sample_foods = [
    {
      id: '1',
      name: 'Orange Chicken',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['china'],
      stars: 4.5,
      imageUrl: 'food-11.jpg',
      tags: ['Ready to serve', 'Chicken', 'Lunch'],
    },
    {
      id: '2',
      name: 'Soup Noodle',
      price: 20,
      cookTime: '20-30',
      favorite: true,
      origins: ['vietnam', 'philippines', 'china'],
      stars: 5,
      imageUrl: 'food-12.jpg',
      tags: ['Soup', 'Lunch'],
    },
    {
      id: '3',
      name: 'Dumpling',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['china', 'us'],
      stars: 3.5,
      imageUrl: 'food-13.jpg',
      tags: ['Ready to serve', 'Dumpling'],
    },
    {
      id: '4',
      name: 'Spring Roll',
      price: 2,
      cookTime: '15-20',
      favorite: true,
      origins: ['china', 'us'],
      stars: 3,
      imageUrl: 'food-14.jpg',
      tags: ['Ready to serve', 'Fried'],
    },
    {
      id: '5',
      name: 'Spicy Chicken',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: ['us', 'asia'],
      stars: 3.5,
      imageUrl: 'food-15.jpg',
      tags: ['SlowFood', 'Chicken'],
    },
    {
      id: '6',
      name: 'Fried noodle"',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['china'],
      stars: 4.0,
      imageUrl: 'food-16.jpg',
      tags: ['Slow', 'Fried', 'Lunch'],
    },
  ];

export const sample_tags = [
    { name: 'All', count: 6}, 
    { name: 'Ready to serve', count: 3},
    { name: 'Chicken', count: 2},
    { name: 'Lunch', count: 3},
    { name: 'SlowFood', count: 1},
    { name: 'Dumpling', count: 1},
    { name: 'Fried', count: 2},
    { name: 'Soup', count: 1},
  ];

export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];